[package]
name = "bayard-proto"
version = "0.1.0"
authors = ["Minoru Osuka <minoru.osuka@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
grpc = "0.6.2"
protobuf = "2.8.2"
raft = "0.4.3"

[build-dependencies]
protobuf-codegen-pure = "2.8.2"
protoc = "2.8.2"
protoc-rust = "2.8.2"
protoc-rust-grpc = "0.6.2"
